# Generated by Django 3.1.2 on 2021-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barpicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='this is an image for bar')),
            ],
            options={
                'db_table': 'barpicture',
            },
        ),
        migrations.AlterModelTable(
            name='slidepicture',
            table='slidepicture',
        ),
    ]
