# Generated by Django 3.1.2 on 2021-10-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelteaacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='', verbose_name='this is an image for the product')),
            ],
            options={
                'db_table': 'first_name',
            },
        ),
    ]
