# Generated by Django 3.1.2 on 2021-10-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_modelteaacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modelteaacher',
            new_name='modelteacher',
        ),
    ]
