# Generated by Django 3.1.2 on 2021-10-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211013_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='', verbose_name='this is an image for bar')),
                ('hlink', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'name',
            },
        ),
    ]
